### ISSUE TITLE
Will be graduating this year

### ISSUE THREAD

**Issue by ArnavGohil** [education/GitHubGraduation-2022#1013]
Hi, I think there's been a mistake. I will be graduating in the coming month, i.e. May 2022

_Originally posted by @ArnavGohil in https://github.com/education/GitHubGraduation-2022/pull/998#issuecomment-1115953024_

**Comment by elisemoe** [comment]
Hi, @ArnavGohil  👋 I've removed your entry from last year's graduation. You should now be able to open a new Pull Request and participate.

Congrats on your graduation!
