### ISSUE TITLE
Did not graduate previous year

### ISSUE THREAD

**Issue by ankushKun** [education/GitHubGraduation-2022#1149]
Hi,
last year (2021) I created the PR, but it was not merged because my Github student pack expired and I hade to reapply for it, due to which I missed the final date for the graduation.

This year I created another PR but was closed with "graduated last year"

Previous year PR -> [#9860](https://github.com/education/GitHubGraduation-2021/pull/9860)
This years PR -> #359 

Please look into it and let me know if something can be done,
Thank you.

**Comment by ankushKun** [comment]
Thanks for the response @elisemoe, but seems like It still closes my PR #1908

**Comment by elisemoe** [comment]
Sorry for the confusion! Do you mind trying once more? We had a problem with the cache but have cleared it now.

**Comment by ankushKun** [comment]
still can't - #2694 
cc: @elisemoe

**Comment by elisemoe** [comment]
Please add a link to you pull request in this issue - https://github.com/education/GitHubGraduation-2022/issues/4290
