### ISSUE TITLE
No previous graduation

### ISSUE THREAD

**Issue by developer22-university** [education/GitHubGraduation-2022#1358]
Hi developer22-university,,
Welcome to graduation!

I'm really sorry! It looks like you've already graduated in a previous year. This is for first time grads!

Originally posted by @github-education in  https://github.com/education/GitHubGraduation-2022/pull/1340#pullrequestreview-960261465

**Comment by developer22-university** [comment]
@github-education  this is really unfair and unjust to us.

**Comment by elisemoe** [comment]
Hi, @developer22-university 👋  It looks like you participated in last year's event. Congrats on your graduation! 

We only allow participation once in the GitHub Graduation yearbook. You're welcome to attend the event on June 11!
