### ISSUE TITLE
Showing I had already graduated last year, even though it did not complete last time

### ISSUE THREAD

**Issue by MrAppu** [education/GitHubGraduation-2022#1539]
I had tried to do last years graduation programme but had not completed it because I had no student developer pack then. Also my directory was wrong. When I tried to apply now, it is showing that I had already done it.
Here is the last years pull request: https://github.com/education/GitHubGraduation-2021/pull/7397

**Comment by MrAppu** [comment]
Do closing the last year's pull request will do anything?

**Comment by elisemoe** [comment]
Hi @MrAppu 👋  I've removed your entry from last year's graduation. You should now be able to open a new Pull Request and participate.

Congrats on your graduation!

**Comment by MrAppu** [comment]
Thank you elisemoe!!

**Comment by MrAppu** [comment]
@elisemoe 
Sorry for pinging you,but the same conflict happened again :(
PR:https://github.com/education/GitHubGraduation-2022/pull/1911

**Comment by elisemoe** [comment]
Sorry for the confusion! Do you mind trying once more? We had a problem with the cache but have cleared it now.

**Comment by MrAppu** [comment]
Nope, still not working D:

**Comment by MrAppu** [comment]
@elisemoe Any updates? I request you to open this issue again :D
