### ISSUE TITLE
Failing automated

### ISSUE THREAD

**Issue by brtobin** [education/GitHubGraduation-2022#1631]
Why?

My repo looks like other successful pull requests

<img width="1226" alt="image" src="https://user-images.githubusercontent.com/24663534/166467017-87e380a6-c258-4bcb-852e-49ef8dec119f.png">

**Comment by hugoFranco21** [comment]
I think I know what the problem is. Deleting that folder and .md file corresponds to a change, that is why it is not letting us merge. Should it work like that? Probably not, but the solution is to just create your files and folder without deleting/changing anything.

**Comment by brtobin** [comment]
You were right @hugoFranco21 , thanks! Also, in the README.md I replaced 'YOUR-USERNAME' with my username which was being rejected
