### ISSUE TITLE
did not graduate last year 

### ISSUE THREAD

**Issue by hitarthkhurana** [education/GitHubGraduation-2022#1877]
even after removing last year's pr, I am not able to create a new pr. it says that I graduated last year

link - [#1860](https://github.com/education/GitHubGraduation-2022/pull/1860)

please fix this

**Comment by elisemoe** [comment]
Thank you both for letting us know! I believe we're running into a problem with cached data. Working on a fix now.

**Comment by MrAppu** [comment]
Same issue here, thank you elisemoe for trying to fix it!

**Comment by zhou-waner** [comment]
the same issue here. PR #2124

**Comment by asheeeshh** [comment]
> Thank you both for letting us know! I believe we're running into a problem with cached data. Working on a fix now.

sorry for the interruption, but I wanted to know about how the bot's logic works at the moment, I think it just checks if the person had opened a PR previous year, if it's really like that then shouldn't we add one more layer of check to see *if the PR was actually merged or not?*

**Comment by elisemoe** [comment]
> > Thank you both for letting us know! I believe we're running into a problem with cached data. Working on a fix now.
> 
> sorry for the interruption, but I wanted to know about how the bot's logic works at the moment, I think it just checks if the person had opened a PR previous year, if it's really like that then shouldn't we add one more layer of check to see _if the PR was actually merged or not?_

Yes! Spot on 😁 We've updated the bot but still had some issues with the cache. You should now be able to open a new PR. Let me know if you still have any trouble with the bot and I'll manually review.

**Comment by ankushKun** [comment]
@elisemoe I still have the same issue with PR #2794 
Will be glad if you could check it and resolve manually ☺️
Thank you

**Comment by AkmalPratama** [comment]
Is it cache problem? Cause I didn't even created PR last year yet still tagged as previously graduated #2855

**Comment by MrAppu** [comment]
@elisemoe It is still a problem. Is it really a cache problem?
