### ISSUE TITLE
No way to mark improvement PRs for the repository itself

### ISSUE THREAD

**Issue by tadd** [education/GitHubGraduation-2022#2048]
Some students (like me) may want to contribute to improving this repository itself, as in #1519.
Is there any plan to provide a way to mark such PRs to distinguish other "add me" PRs?

I think there are currently two problems.

1. Unconditional GitHub Actions execution
    * Unnecessary checks ("graduation judgment") yield red signs 🚫 that may make merging hard
    * Time-consuming and increases carbon emissions 🌐😢
2. Increased workload for GitHub staff
    * First, thanks for working for students like us! ✨
    * Identifying repository improvement PRs among the 7,500+ majority "add me" PRs is a tough task, in my opinion

If some markers or labels are present, they could mitigate the problems.

* The GitHub Actions program can detect them mechanically and can skip needless execution
* GitHub staff (who review this like you) can identify and prioritize PRs with them.

I appreciate your consideration.

### PS

Thank you again for providing such an exciting and fun event. As a student who had little time to engage with other students due to COVID-19, I am grateful for this opportunity to realize that I have "classmates" worldwide!

**Comment by elisemoe** [comment]
Thanks for your message @tadd 💖 💖

We're a little hesitant to test bot changes in production but are adding this to our wish list for next year! 😁 If you use the "enhancements" label on a PR, we'll be sure to check and review any contributions!

I'll also leave this Issue open if you want to link to a PR for review.

**Comment by elisemoe** [comment]
Update: the "enhancements" label is not excluded from the CI pipeline ✨  Thanks for the idea!!

**Comment by asheeeshh** [comment]
The will still check the PR atleast once according to me, as we can't add the label ourselves like #2461 , maybe checking before the PR is submitted that if it's enhancement or yearbook addition and adding a label could help.

**Comment by juanpflores** [comment]
If you add the `enhancement` label, the bot won't review it and we can check it out afterwards 😉

**Comment by asheeeshh** [comment]
I can't add the labels myself though, would like you to check this pr #2461 as it was closed by the bot.

**Comment by juanpflores** [comment]
Hey @asheeeshh 👋🏼 
Thanks for making such a great question. I have left a note for the team to consider new methods for signaling improvements on the repository. There is a lot of thought that needs to go to this to make sure this improvements don't get lost in a sea of pull request. I'll close this issue for now as not planned but definitely appreciate you for raising this issue
