### ISSUE TITLE
Update shipping information ➡️

### ISSUE THREAD

**Issue by StoreksFeed** [education/GitHubGraduation-2022#2642]
This issue is open for requests to change your shipping address. Resubmit the shipping form and ping staff member

**Comment by juanpflores** [comment]
Yes! Resubmit the form, ping us and we can update it ✅

**Comment by StoreksFeed** [comment]
@juanpflores update the address for PR #538 please

**Comment by Mohnish226** [comment]
@juanpflores  I also had to update my address for [#90](https://github.com/education/GitHubGraduation-2022/pull/90). Please use the most recent address; I have resubmitted the form. Thank you very much

**Comment by Xunzhuo** [comment]
Me too, please update my address for https://github.com/education/GitHubGraduation-2022/pull/1386

**Comment by juanpflores** [comment]
✅ Update all three!

**Comment by dsrkafuu** [comment]
Hi @juanpflores,

I found that the address I previously submitted may have had some problems receiving mail months later, so I resubmitted the form with my new address and my legal name.

Can you update those for #2614?

**Comment by juanpflores** [comment]
✅ @dsrkafuu updated your address with the latest information.

**Comment by anishagg17** [comment]
Hi @juanpflores,

I've submitted the form, can you please update #4239

**Comment by antoniomd-fi** [comment]
Hi @juanpflores,

I submitted two diferents forms. Can you use the last form to my shipping?, that have the correct address.

I'm #3925.

Thanks.

**Comment by moli-debugger** [comment]
Hi @juanpflores,

I submitted two different forms. Can you use the last form to my shipping please?, that have the correct address.

I'm #4607

**Comment by mrepol742** [comment]
Hi @juanpflores,

I submitted two different forms. Can you use the last form to my shipping please?, that have the correct address.

I'm #35

Thanks.

**Comment by juanpflores** [comment]
@anishagg17 ✅ we used the latest form you submitted
@antoniomd-fi we only found one form with your username on it
@moli-debugger ✅ updated
@mrepol742 ✅ updated

**Comment by antoniomd-fi** [comment]
@juanpflores  I've just resubmitted the form with te correct address.

Thanks!

**Comment by Nerodacles** [comment]
Hi, @juanpflores,
Please update my shipping address please? PR #2460

**Comment by juanpflores** [comment]
Hey @OmarDev100 I'm not entirely sure which shipping company we will be using. I will pass the note along to see what options we have.

**Comment by juanpflores** [comment]
✅ Updated @antoniomd-fi @Nerodacles

**Comment by Shrit1401** [comment]
@juanpflores  I have updated my details in the shipping form kindly check

**Comment by juanpflores** [comment]
✅ @Shrit1401 updated

**Comment by shaikhul** [comment]
❓ I put my US address as shipment but will be traveling next week, wondering whats the probability to get the shipment before 22nd or should I go ahead and update my shipping address? @juanpflores

**Comment by juanpflores** [comment]
> ❓ I put my US address as shipment but will be traveling next week, wondering whats the probability to get the shipment before 22nd or should I go ahead and update my shipping address? @juanpflores

Swag won't be delivered before the 22nd

**Comment by Loner291999** [comment]
@juanpflores pls can you update the shipping info for https://github.com/education/GitHubGraduation-2022/pull/781#event-6541824993 , i sent a new form thanks!

**Comment by holiq** [comment]
@juanpflores I have submit on the form but did not receive a confirmation email, is it really like that? Do I have to fill out the form again?

**Comment by DominusTrax** [comment]
@juanpflores update the address for PR #5578 please

**Comment by wu000168** [comment]
(PR#6152) When approximately will the swags be sent out? I will be moving a few times over the summer and I am wondering whether I will need to change address because of that.

**Comment by mariiiiiq** [comment]
@juanpflores Hi, I just submitted another shipping information, because we will be moving next month. Kindly update PR #7643, thank you.

**Comment by ProgMiner** [comment]
@juanpflores Hello, I've just resubmit the form because I've just remember that my previous send had incorrect address. Could you update my address please? PR #7695

**Comment by juanpflores** [comment]
✅ Updated @Loner291999 @holiq @DominusTrax @mariiiiiq @ProgMiner 

@wu000168 We'll be sending the packages in the next couple of weeks

**Comment by juanpflores** [comment]
@AlexDev404 Someone from the team will review your PR in the next couple of days ⭐

**Comment by shreyask21** [comment]
@juanpflores Could you please update my shipping address too? 

[My PR](https://github.com/education/GitHubGraduation-2022/pull/8074)

Thanks!

**Comment by parekh0711** [comment]
@juanpflores Could you please update my shipping address too?

[PR](https://github.com/education/GitHubGraduation-2022/pull/250)

Thanks!

**Comment by MrAppu** [comment]
@juanpflores Can we change the shipping address now?

**Comment by Gleaner2021** [comment]
Hi @juanpflores,
Could you please help me to update my shipping address? #7429 I have re-submitted the form.
Thank you.

**Comment by juanpflores** [comment]
✅ updated @shreyask21 @parekh0711 @Gleaner2021 

@MrAppu Try submitting a new form using the link in the readme.

**Comment by ashutoshkrris** [comment]
Hey @juanpflores 
Could you please help me update my shipping address for the PR #1054
I've resubmitted the form.

**Comment by moni-roy** [comment]
Hi @juanpflores, I have updated my address for PR [#2229](https://github.com/education/GitHubGraduation-2022/pull/2229). Please use the most recent address. I have resubmitted the form. Thank you!

**Comment by MrAppu** [comment]
Thank you for the reply @juanpflores , I would like to know how long it will take to ship to a place, for example, India. I will move to another place next month. Then only I can decide if I want to change the shipping form.

**Comment by urlocalmadman** [comment]
@juanpflores could you please update to my latest shipping form? Needed to update address. im #2884

**Comment by Ekmand** [comment]
@juanpflores Thought I put my stuff in right, but I've been second guessing myself so I just resubmitted the form. I'm PR [#349 ](https://github.com/education/GitHubGraduation-2022/pull/349)

**Comment by Abhishek12345679** [comment]
@juanpflores can you change the shipping information for PR #6048. Resubmitted the shipping form with the new address.

**Comment by Daniel-Fan** [comment]
Hi @juanpflores 

I have re-submitted the shipping form with the updated address. My PR was https://github.com/education/GitHubGraduation-2022/pull/4243.

Could you please help to update the shipping address if the package has not be shipped. Thank you!

**Comment by delzadbamji** [comment]
Hey @juanpflores 
Is there a way to confirm my address on file?
Or the delivery status of the package?

**Comment by azizulabedinazmi** [comment]
Hello 👋
I'm a student of Computer Science And Engineering at East West University, Bangladesh.
It's been a while of GitHub Graduation 🎓 2022. But I still don't receive any  letter and custom trading card 💌 .
PR #7863

**Comment by lasr21** [comment]
@AlexDev404 Hi there, we are still sending the cards for this year's graduation. Please bear with us

**Comment by AlexDev404** [comment]
> @AlexDev404 Hi there, we are still sending the cards for this year's graduation. Please bear with us

Okay sure @lasr21, no problem! 
Thanks for the update, it means a lot.

Just was a bit worried that my submission wasn't received. 
Thanks for the clarification.

**Comment by Che-Zhu** [comment]
Hi @juanpflores . Could you please update my shipping address? I moved to a new place recently. My PR was #7144.

Thanks in advance!

**Comment by anandjagadeesh** [comment]
> 

Hi Team,

Have you started shipping out the cards? I will be moving out of my current address in mid-August and wanted to know if the shipment would happen before that as after that time there won't be anyone to collect it for me and I don't know my next accommodation's address yet. If this is the wrong thread, kindly redirect me to the right place!

Thanks in advance.

Thanks,
Anand (uname: anandjagadeesh) (PR:#1500)

**Comment by lasr21** [comment]
Hi there, we have already sent all the cards. Postal service in each region it's different. Some arrive in weeks. Other takes months. It's out of our control.

**Comment by azizulabedinazmi** [comment]
Still don't receive any letter and custom trading card 💌 .
PR #7863

**Comment by lasr21** [comment]
> Still don't receive any letter and custom trading card 💌 . PR #7863

We're seeing up to 5 month delivery times for international shipments with the delays from covid. If you have not seen anything by then, you're welcome to get back in touch with us.

Unfortunately, we don't have tracking on the shipments.

**Comment by icorbrey** [comment]
@lasr21 I'm in the continental US and have not received my stuff yet. Should I reach out to someone?

**Comment by thegautamkumarjaiswal** [comment]
I am a GitHub Graduation 2021 student and one of 7500 graduate of 2021. I haven't received my graduation swags and I have again updated my address with this. Can you please tell Wheatherwill.I recieve my swags of not? @juanpflores

**Comment by HarishGuragol** [comment]
Hi team 

I have not received the shipment of my graduation swags 2022. I had filled both the forms ,can you please update on it 
Username : HarishGuragol
PR  #386

**Comment by wu000168** [comment]
#6152 I am moving and have not received the package either in continental US. I have submitted another address form for the new address just in case. Any update on why so many of us are having delivery issues?

**Comment by lasr21** [comment]
@icorbrey @thegautamkumarjaiswal @wu000168  Hello, On the first week of September, we will send a form to resend the missing cards. Stay tuned. Thanks for your patience

**Comment by ghost** [comment]
Hello  @lasr21, I am not able to find the the form for missing cards. Please update it.

**Comment by wu000168** [comment]
> Hello  @lasr21, I am not able to find the the form for missing cards. Please update it.

I still have not received a new form either.

**Comment by ghost** [comment]
> > Hello  @lasr21, I am not able to find the the form for missing cards. Please update it.
> 
> I still have not received a new form either.

You can find it in Readme file.

**Comment by ghost** [comment]
https://github.com/education/GitHubGraduation-2022

**Comment by azizulabedinazmi** [comment]
I still don't receive any letter and custom trading card 💌 .
PR #7863

**Comment by lasr21** [comment]
> I still don't receive any letter and custom trading card 💌 . PR #7863

please check https://github.com/education/GitHubGraduation-2022/issues/8395

**Comment by Jarvis-Ank** [comment]
I've submitted a reprint form can you check if it is active.

**Comment by Jarvis-Ank** [comment]
> I've submitted a reprint form can you check if it is active.

@lasr21
