### ISSUE TITLE
Unable to add to GitHubGraduation-2022

### ISSUE THREAD

**Issue by itsRkator** [education/GitHubGraduation-2022#2791]
My PR closed without merging with the response that I graduated the previous year but I'm graduating this year only.

I'm attaching my Institute ID card herewith for your reference.

**Comment by harshit-paneri** [comment]
Hey ROHITASH,
 What comment is mention in your PR ?

**Comment by itsRkator** [comment]
Hi itsRkator,
Welcome to graduation!

I'm really sorry! It looks like you've already graduated in a previous year. This is for first time grads!

<img width="1246" alt="image" src="https://user-images.githubusercontent.com/43729042/166720974-e7aa1bfa-abb0-4d93-a1f7-4c1e148a4fcf.png">

**Comment by itsRkator** [comment]
Yes

**Comment by harshit-paneri** [comment]
delete that repo, then try it again

**Comment by itsRkator** [comment]
I already deleted last year's GitHubGraduation repo. Still facing same issue.

**Comment by harshit-paneri** [comment]
Did you send any PR in last year Repo if yes so is it merged or not ?

**Comment by elisemoe** [comment]
Hi @itsRkator 👋 sorry for the frustration! Can you please open a new PR and post the link here? I'll manually review it.

**Comment by itsRkator** [comment]
Hi @elisemoe,
Here is the link to my PR: https://github.com/education/GitHubGraduation-2022/pull/4288

**Comment by itsRkator** [comment]
Hi @elisemoe 👋🏻 , Thank You for the help 😁.
