### ISSUE TITLE
Bot saying I'm not in the Student Developer Pack when I am

### ISSUE THREAD

**Issue by Nanofaux** [education/GitHubGraduation-2022#2945]
The bot says that it's "not seeing a valid student developer pack approval", yet I am approved and I can confirm this when I go to the site
![image](https://user-images.githubusercontent.com/26722651/166683049-d39e3353-23a6-4ff2-91de-94cacf623337.png)
How can I fix this?

**Comment by gabuvns** [comment]
I'm currently facing the same problem here!

**Comment by juanpflores** [comment]
✅ I have validated that both @gabuvns and @Nanofaux have a valid SDP
ℹ️ _@Nanofaux I don't appreciate that your website Rick Rolled our team..._

**Comment by 54yyyu** [comment]
I have the same issue too!

**Comment by juanpflores** [comment]
✅ Fixed all of them. 

Solution: If you experience the problem you can request another review from the bot. If it fails again give it a couple of hours to recover. Otherwise ping me in this issue and I'm happy to jump in 🔬

**Comment by Nanofaux** [comment]
@juanpflores I tried after a few hours and it still says I'm not eligible again. The PR is [here](https://github.com/education/GitHubGraduation-2022/pull/3253) if you need to see

**Comment by juanpflores** [comment]
> @juanpflores I tried after a few hours and it still says I'm not eligible again. The PR is [here](https://github.com/education/GitHubGraduation-2022/pull/3253) if you need to see

Weird. I just requested a review again and it found you. I'll take a look into this 👀

**Comment by gabuvns** [comment]
Everything good here! Thanks for the help!

**Comment by yashash1511** [comment]
@juanpflores it still says no _I'm not seeing a valid student developer pack approval_ #3727

**Comment by n1k0ver3E** [comment]
@juanpflores Hi, I graduate in Feb. 2022 so the SDP has been out of date. Is it possible for me to join the event?
I register SDP in 2020.
![image](https://user-images.githubusercontent.com/14194564/167169787-4cba7fb8-52f5-4ae9-8486-e1e6f7c867d1.png)


My PR here ➡️  #4161

**Comment by yashash1511** [comment]
@juanpflores my PR#3727 bot still says
> I'm not seeing a valid student developer pack approval

![image](https://user-images.githubusercontent.com/89068816/166994436-d5e14ee7-2d77-4a9f-b7ab-a5bc67d45ff4.png)
i even got it reapproved yesterday just in case

**Comment by juanpflores** [comment]
I have updated both ⭐ @yashash1511 @n1k0ver3E

**Comment by dsshivamsingh** [comment]
@juanpflores  I am facing the same issue , I have followed the whole guideline  and i also have the github student developer pack but my pr is being closed automatically as checker says I don't have GSDP , adding my PR here[https://github.com/education/GitHubGraduation-2022/pull/4066](url)

**Comment by juanpflores** [comment]
@dsshivamsingh You're all set ✅

**Comment by HydroPlume** [comment]
@juanpflores Having the same issue with my pull request #5712, despite having been verified last September:

![proof of verification](https://user-images.githubusercontent.com/32257234/168507460-f8ffbb8a-d3a3-4851-807e-aded5e90c271.png)

**Comment by juanpflores** [comment]
✅ validated @HydroPlume
