### ISSUE TITLE
Bad Gateway on Apply Now

### ISSUE THREAD

**Issue by prskid1000** [education/GitHubGraduation-2022#300]
<img width="1312" alt="Screenshot 2022-05-03 at 12 37 43 PM" src="https://user-images.githubusercontent.com/42976809/166415941-31044145-142d-4f3d-b7ef-98af036fdcb0.png">

**Comment by prskid1000** [comment]
You have been verified as a student with the GitHub Student Developer Pack. Not yet a part of the Pack? [Apply here](https://education.github.com/discount_requests/student_application?utm_source=2022-06-11-GitHubGraduation).  This link not working on Safari(Monterey)

**Comment by 25077667** [comment]
Me too.

**Comment by MuhammadAhmed8** [comment]
Same here. Bad Gateway error.

**Comment by e6654321** [comment]
I have the same issue, using chrome and edge

**Comment by juanpflores** [comment]
Closing this issue as the problem has been resolved
