### ISSUE TITLE
PR template has 2021 calendar event link

### ISSUE THREAD

**Issue by RyanCallahan312** [education/GitHubGraduation-2022#305]
The event link in the pr template goes to https://calendar.google.com/calendar/u/0/r/eventedit?dates=20210605T160000Z/20210605T173000Z&text=GitHub+Graduation+%F0%9F%8E%93&location=https://www.twitch.tv/githubeducation&details&sf=true

This leads leads to the 2021 event
![image](https://user-images.githubusercontent.com/16870158/166416030-33f52e0a-4132-41c0-a3c1-65ef32f25a3c.png)

**Comment by juanpflores** [comment]
✅ The link was updated

**Comment by juanpflores** [comment]
Thanks for reporting this 👾
