### ISSUE TITLE
Added Polish translation

### ISSUE THREAD

**Issue by Nevalicjus** [education/GitHubGraduation-2022#3196]
I've translated the README to Polish in #1922

**Comment by juanpflores** [comment]
Thanks for submitting this translation @Nevalicjus ❇️

**Comment by juanpflores** [comment]
✅ LGTM will merge in a few

**Comment by Nevalicjus** [comment]
I've fixed the translation a bit in #4049 😅

**Comment by juanpflores** [comment]
Updated !
