### ISSUE TITLE
PR merged but no message

### ISSUE THREAD

**Issue by Mxrcon** [education/GitHubGraduation-2022#3231]
Hey :wave:,

my PR was merged (https://github.com/education/GitHubGraduation-2022/pull/2060) but i haven't received the congratulations message that everyone recieved, is there any problem with my participation?

Kindly, Davi

**Comment by juanpflores** [comment]
The bot took some extra time to congratulate you ⭐

**Comment by Mxrcon** [comment]
thank you @juanpflores
