### ISSUE TITLE
The problem of the bot stating that you have previously graduated remains. 

### ISSUE THREAD

**Issue by MrAppu** [education/GitHubGraduation-2022#3306]
I tried again and again for 7 times and still is not working. I thought the open pull request of the 2021 was conflicting with it. So I closed it and tried again. Still it is not working :-(

**Comment by nameisazeem** [comment]
I am also facing the same issue here.

**Comment by MrAppu** [comment]
@elisemoe Any updates?

**Comment by yashpaneliya** [comment]
Issue resolved? @MrAppu

**Comment by MrAppu** [comment]
Yash, try looking for your name in the _data .

**Comment by MrAppu** [comment]
I saw my folder there lol

**Comment by yashpaneliya** [comment]
Mine is not there!

**Comment by MrAppu** [comment]
Wait a minute Yash, [oh man you had closed the request last time eh](https://github.com/education/GitHubGraduation-2021/pull/8055). I think elisemoe or juan is your only hope :(

**Comment by yashpaneliya** [comment]
> Wait a minute Yash, [oh man you had closed the request last time eh](https://github.com/education/GitHubGraduation-2021/pull/8055). I think elisemoe or juan is your only hope :(

Already tried to tag them

**Comment by MrAppu** [comment]
Mention them in the issues , Lets hope they see it tonight and before 7.5k pull request
