### ISSUE TITLE
My official graduation year is 2022 but it is showing you're previously graduated.

### ISSUE THREAD

**Issue by nameisazeem** [education/GitHubGraduation-2022#3363]
My official graduation year is 2022, but it shows you're previously graduated while creating a pull request. Kindly do the needful.

**Comment by harshit-paneri** [comment]
It may be you did it last year also, or you fork 2021 repo also

**Comment by Abhishek4uh** [comment]
@nameisazeem same with me, have you found any solution?

**Comment by nameisazeem** [comment]
Not yet @Abhishek4uh

**Comment by elisemoe** [comment]
Thanks, everyone for letting us know! Your PRs have now been merged.
