### ISSUE TITLE
Added Hindi translation

### ISSUE THREAD

**Issue by Saket-Upadhyay** [education/GitHubGraduation-2022#3389]
Hi, I've added the Hindi Translation of README.md :) #3384

**Comment by Saket-Upadhyay** [comment]
please list it as "हिन्दी" in the language list, it will help people who speak Hindi to find it easily.

**Comment by harshit-paneri** [comment]
Hey @Saket-Upadhyay 👋🏻, 
It's really a nice thing done by you, It helps lot of people, I have a suggestion to make hyper link of some things like **add calendar** , **community** and etc.

**Comment by Saket-Upadhyay** [comment]
Thanks, @harshit-paneri, I've already added the Calendar and Community link as in mentioned in the main Readme.md. You can check the same from Line 85 to 90 in the file. Let me know if that's what you were suggesting?

**Comment by harshit-paneri** [comment]
Ok , it's nice 
Wait till when they assign you and then again send a new PR
