### ISSUE TITLE
Custom Trading Card Edit

### ISSUE THREAD

**Issue by OmarDev100** [education/GitHubGraduation-2022#3413]
Hello @github-education @elisemoe!

Kindly, I would request an edit in my **Custom Trading Card**.

I have 2 **GitHub** accounts:

- **OmarDev100 - I have the Student Pack in it - I don't use it a lot**
- **Omar8345 - I don't have the Student Pack in it - I use it a lot - My Main Account**

So as you would expect, I would like to have a trading card for **Omar8345** as I have more activity in it and such on. Thank you!

**Comment by juanpflores** [comment]
✅ updated the username

**Comment by OmarDev100** [comment]
Thank you
