### ISSUE TITLE
Russia was not in shipping form

### ISSUE THREAD

**Issue by ATLANTer** [education/GitHubGraduation-2022#3531]
When I sent shipping form for the first time, I not found Russia in country list and I selected Belarus. Recently I decided to look again and I found Russia in country list. I sent shipping form for the second time. It is will be ok?

**Comment by elisemoe** [comment]
Thanks for letting us know @ATLANTer! Apologies for the confusion. I've checked both your submissions are updated to Russia and should be good ✅
