### ISSUE TITLE
I am approved for the student dev pack but still it show I'm not seeing a valid student developer pack approval

### ISSUE THREAD

**Issue by yashash1511** [education/GitHubGraduation-2022#3752]
It says 'I'm not seeing a valid student developer pack approval' even when I am #3727 

![image](https://user-images.githubusercontent.com/89068816/167006047-e54ff121-2de7-427e-a14a-bb170893da96.png)
i even submitted a new request just in case and got approved again

**Comment by asheeeshh** [comment]
https://github.com/education/GitHubGraduation-2022/issues/2945#issuecomment-1117981749

**Comment by yashash1511** [comment]
> [#2945 (comment)](https://github.com/education/GitHubGraduation-2022/issues/2945#issuecomment-1117981749)

ok thank you
