### ISSUE TITLE
Can't sign up as it says Previously Graduated.

### ISSUE THREAD

**Issue by yashpaneliya** [education/GitHubGraduation-2022#4034]
Can't sign up as it says Previously Graduated.

Definitely do not have my data in https://github.com/education/GitHubGraduation-2021/tree/main/_data or https://education.github.com/graduation/yearbook?sort=az&page=-1&search=yashpaneliya

Please resolve this issue @github-education @elisemoe @juanpflores 

PR for Graduation-2022: #4027

**Comment by MrAppu** [comment]
@elisemoe  How about making the bot look at the yearbook data? Sorry if the bot is already doing that.

**Comment by AnkushSinghGandhi** [comment]
me too

**Comment by elisemoe** [comment]
Hi everyone 👋 sorry for the frustrations!

@yashpaneliya @MrAppu @nameisazeem @AnkushSinghGandhi your PRs have all now been merged.
