### ISSUE TITLE
Reviewer says that i've not completed the form.

### ISSUE THREAD

**Issue by chiquidev** [education/GitHubGraduation-2022#4369]
I've succesfully completed the form, but the reviewer says that i've not sended it. How can I solve that?
![image](https://user-images.githubusercontent.com/38810865/167250372-b57a4f30-b47c-4bc8-abea-7bed7239970d.png)

**Comment by VellichorAT** [comment]
Maybe you have mistaken your username (chiquidev) and nickname(Chiqui) in the form? I've meet this problem before.

**Comment by chiquidev** [comment]
In the GitHub Username field I put "chiquidev", this is what I should have put, right?

**Comment by chiquidev** [comment]
Solved, i've deleted the form and re-maked it again ;)
