### ISSUE TITLE
I'm not yet graduate

### ISSUE THREAD

**Issue by Harshshahi99** [education/GitHubGraduation-2022#4499]
**Hi Harshshahi99,**
**Welcome to graduation!**

I'm really sorry! It looks like you've already graduated in a previous year. This is for first time grads!

_Originally posted by @github-education in https://github.com/education/GitHubGraduation-2022/pull/4498#pullrequestreview-965355928_

**Comment by juanpflores** [comment]
✅ Reviewed and soon to be merged
