### ISSUE TITLE
I 'am not graduated and closing PRs 

### ISSUE THREAD

**Issue by anjali1102** [education/GitHubGraduation-2022#4530]
hey I am Anjali, my PRs are automatically getting closed saying you're graduated . I am not graduated, I will be graduating in  coming June 2022
#505
#2400
are my closed PRs 

can you please look into this 😥

**Comment by RupomChowdhury** [comment]
it is what it is.. check in 2021's PR list..

**Comment by RupomChowdhury** [comment]
it is what it is...now sleep!  https://education.github.com/graduation/yearbook?sort=az&page=27&search=anjali1102#anjali1102

**Comment by juanpflores** [comment]
Found in last year's graduation
