### ISSUE TITLE
Not Previously Graduated going to graduate in 2022

### ISSUE THREAD

**Issue by aryangulati** [education/GitHubGraduation-2022#459]
**Hi aryangulati,**
**Welcome to graduation!**

I'm really sorry! It looks like you've already graduated in a previous year. This is for first time grads!

_Originally posted by @github-education in https://github.com/education/GitHubGraduation-2022/pull/240#pullrequestreview-959996425_

**Comment by aryangulati** [comment]
Thank you but again it's labeling PR #1873  as previously graduated

**Comment by elisemoe** [comment]
> Thank you but again it's labeling PR #1873 as previously graduated please review it Thank you for your kind help

Sorry for the confusion! Do you mind trying one more time? We had a problem with the cache but have clear last year's data now.

**Comment by aryangulati** [comment]
Thank you so much 
But I think the issue is still not resolved yet for me
PR #2664

**Comment by elisemoe** [comment]
Please add a link to your Pull Request in this Issue - https://github.com/education/GitHubGraduation-2022/issues/4290
