### ISSUE TITLE
I do not admit the length of my name

### ISSUE THREAD

**Issue by eduantvarmau** [education/GitHubGraduation-2022#5224]
My name has more than 28 characters,  name is Eduardo Antonio Vargas Mauricio

**Comment by lasr21** [comment]
may I suggest that you use only your first name and last, so it could fit the length requirements Eduardo Vargas could work or Eduardo A. Vargas, and if you want to use your full name, perhaps Eduardo A. Vargas Mauricio

**Comment by eduantvarmau** [comment]
I like this change:
Eduardo A. Vargas Mauricio
