### ISSUE TITLE
Request to remove my name from yearbook

### ISSUE THREAD

**Issue by Apitpr0** [education/GitHubGraduation-2022#5311]
Hello there, 
just got an update from university that i will be graduating in 2023 not 2022
So can you guys remove my name from this year's yearbook?
Thanks :)

**Comment by OmarDev100** [comment]
Oh, such sad 4 u, good luck next year :wink:

**Comment by Apitpr0** [comment]
> 

Yeah man.. Sure thing will make sure next year i pass with flying colors
