### ISSUE TITLE
Can't sign up as it says Previously Graduated.

### ISSUE THREAD

**Issue by krish-pabani** [education/GitHubGraduation-2022#5358]
Can't sign up as it says Previously Graduated.

Definitely do not have my data in https://github.com/education/GitHubGraduation-2021/tree/main/_data or https://education.github.com/graduation/yearbook?sort=az&page=-1&search=krish-pabani

Please resolve this issue @github-education @elisemoe @juanpflores

PR for Graduation-2022: #4636

**Comment by daminebenq** [comment]
https://github.com/education/GitHubGraduation-2021/pull/1657 samething here
I didn't receive my SWAG shipment yet.

**Comment by daminebenq** [comment]
Hello @juanpflores,

Can you please review this and provide me with more informations about it? https://github.com/education/GitHubGraduation-2021/pull/1657
I would love to receive the SWAG kit from Github <3 

Cordially.
Mohamed.

**Comment by juanpflores** [comment]
Do you mind sending us DM on Twitter for our team to follow up on this?
