### ISSUE TITLE
Inconsistent "save the date" links

### ISSUE THREAD

**Issue by Rishit-dagli** [education/GitHubGraduation-2022#55]
There are 2 "Save the Date" links in the document:

- Under "How to join the Class of 2022"
- Under "Graduation Day 🎓"

Both of these links show different times and the first one is flagged invalid by Google Calendar as well, please see the screenshot.

![image](https://user-images.githubusercontent.com/39672672/166411864-5b7b9e1c-64f5-40dc-9d21-32c62a948c51.png)

**Comment by elisemoe** [comment]
Thanks so much for letting us know @Rishit-dagli! I'll go ahead and update the links.

The live event is on June 11 at 9 am Pacific Time.
