### ISSUE TITLE
UAE country not available in Airtable shipping form

### ISSUE THREAD

**Issue by OmarDev100** [education/GitHubGraduation-2022#556]
I am searching for United Arab Emirates (UAE) in the shipping form but I cannot find it, please add it ASAP @elisemoe

**Comment by Loner291999** [comment]
same

**Comment by OmarDev100** [comment]
yeah

**Comment by IPRIT** [comment]
Same with Russia and other different countries

**Comment by OmarDev100** [comment]
but like some countries are not having like any restrictions but they are not listed btw

**Comment by OmarDev100** [comment]
and PRs are growing so high, and if they didn't reply, i will almost lose my chance

**Comment by elisemoe** [comment]
Thanks, everyone for letting us know about the mistake ❤️ 

I've added UAE to the shipping form.

**Comment by OmarDev100** [comment]
Thanks!!!
