### ISSUE TITLE
GitHub says I'm Graduated but currently I'm persuing my Graduation 

### ISSUE THREAD

**Issue by SushantSingh2** [education/GitHubGraduation-2022#5669]
Hi, 
### GitHub says I'm Graduated but currently I'm persuing my Graduation.
Please check again and resolve my issue.
I had uploaded my  college ID card which has clearly written 19-2022 batch.

To, @github-education ,

**Comment by Sanan4li** [comment]
Hi Sushant, 
Please mention your PR link here https://github.com/education/GitHubGraduation-2022/issues/4290

**Comment by juanpflores** [comment]
Hi there! I removed your badge since it has a ton of personal data. Closing this issue as we were unable to find your PR
