### ISSUE TITLE
Can't apply for student dveloper pack

### ISSUE THREAD

**Issue by singh08prashant** [education/GitHubGraduation-2022#608]
My student developer pack expired last year and I am not able to re-apply for the same.
My PR to this repo is failing.

**Comment by PDPENG** [comment]
> My student developer pack expired last year and I am not able to re-apply for the same.
My PR to this repo is failing.

Ah, can I reapply if the student bag has expired?

**Comment by elisemoe** [comment]
Hello 👋  can you please tell me more about why you're not able to re-apply? 

GitHub Graduation is an event for students verified with the Student Developer Pack, and having a valid Pack is required.

**Comment by elisemoe** [comment]
> > My student developer pack expired last year and I am not able to re-apply for the same.
> > My PR to this repo is failing.
> 
> Ah, can I reapply if the student bag has expired?

Yes! You are welcome to re-apply.

**Comment by tulika9414** [comment]
The Student developer form is not opening

**Comment by elisemoe** [comment]
> The Student developer form is not opening

Here's [the application form](https://education.github.com/discount_requests/student_application?utm_source=2022-06-11-GitHubGraduation).
