### ISSUE TITLE
Failed to add .md file

### ISSUE THREAD

**Issue by timothy-brian** [education/GitHubGraduation-2022#6868]
I'm having trouble adding a markdown file containing profile information. My application has been rejected many times. Please help
![image](https://user-images.githubusercontent.com/73934414/169658334-2ecef1fc-c567-4643-ac6b-ff79839b6e96.png)
![image](https://user-images.githubusercontent.com/73934414/169658378-14a736e0-ffca-445d-81a0-d7a09cec4d95.png)

**Comment by juanpflores** [comment]
This pull request was merged
