### ISSUE TITLE
Questions about the institution name field

### ISSUE THREAD

**Issue by busybox11** [education/GitHubGraduation-2022#7121]
Hey!
I'm currently filling out the form for this graduation project, and I have some questions about the institution's name field (and also something that is related to the other fields too).
There is a flag on the name before the comment. Should we keep it?
Also, so I have to add the school's city on the field?

One more thing. It is indicated that no special characters are allowed. Does accented letters count as that or not? My name and school contained accented characters and I don't want to mess this up haha.

Thanks a lot for this awesome project!

**Comment by juanpflores** [comment]
You got it all right. On the form, we need you to add the city where you live
