### ISSUE TITLE
Add Vi1234sh12 to Github Graduation 2022 

### ISSUE THREAD

**Issue by Vi1234sh12** [education/GitHubGraduation-2022#7656]
Signed-off-by:  Vi1234sh12 dhanurevishal2@gmail.com

### Application to the Class of 2022🎓

This pull request template helps you complete an application to the Class of 2022. Use the checklist below to verify you have followed the instructions correctly.

### Checklist ✅

- [x] I have read the instructions on the README file before submitting my application.

- [x] I made my submission by creating a folder on the _data folder and followed the naming convention mentioned in the instructions 
       (<username>) and markdown file.
- [x] I have submitted a [swag shipping form](https://airtable.com/shrVMo8ItH4wjsO9f).
 - [x] I have used the Markdown file template to add my information to the Year Book.
 - [x] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
 - [x] I understand I should not tag or add a reviewer to this Pull Request.
 - [x] I have [added the event](http://www.google.com/calendar/event?action=TEMPLATE&dates=20210605T160000Z%2F20210605T173000Z&text=GitHub%20Graduation%20%F0%9F%8E%93&location=https%3A%2F%2Fwww.twitch.tv%2Fgithubeducation&details=) to my Calendar.

**Comment by juanpflores** [comment]
Hi @Vi1234sh12 👋🏼 
You'll need to submit your application to the event by submitting a pull request. Would recommend reading the README on this repository to read the instructions
