### ISSUE TITLE
Pull request not merged yet

### ISSUE THREAD

**Issue by dips4982** [education/GitHubGraduation-2022#7738]
I was going through the pull request that are being merged and after pull request #6475 directly pull request #6582 has been merged. My pull request #6517 has the tag ready to merge and satisfies all the criteria has not been merged yet. Github team can you please look into this?
thank you

**Comment by devansh2805** [comment]
Similar case, my pull request is tagged ready to merge. Merged PRs are jumped from #6703 to #6822. Mine is #6746.

**Comment by melvincwng** [comment]
Likewise, my PR #6300 has been skipped.  Can the Github team look into this as well?

https://github.com/education/GitHubGraduation-2022/pull/6300

**Comment by saicharansigiri** [comment]
Same happened With my Pull request  too,  mine was #6349  but they Directly Jumped from #6252  to #6355

**Comment by Harindulk** [comment]
same problem 🥲🥲, #6542

**Comment by iamayushy** [comment]
same issue #6547

**Comment by hannest03** [comment]
same with mine #6956

**Comment by melvincwng** [comment]
Thanks @juanpflores for the help provided :) !

**Comment by abhay-ag** [comment]
Same happened with my pull request too, mine was #7769 but they skipped from #7227 to #7841  
@elisemoe @juanpflores can you please help me out

**Comment by abhay-ag** [comment]
GitHub Team please help!! @elisemoe and @juanpflores please look into this issue!

**Comment by might4** [comment]
My pr(#7414) as referenced in issue #7971 is also not merged yet.

**Comment by ReadChart** [comment]
Mine is #7913 and also skipped, @elisemoe @juanpflores can you please help me out, thanks

**Comment by hariscs** [comment]
they skipped mine too, #7492

**Comment by obrobrio2000** [comment]
My PR #8113 as referenced in issue #8175 is also not merged yet :(

**Comment by AlexDev404** [comment]
@elisemoe @juanpflores Can you please merge mine as well? :(

https://github.com/education/GitHubGraduation-2022/pull/8142

**Comment by juanpflores** [comment]
All of this pull requests were merged!
