### ISSUE TITLE
Can't fix it

### ISSUE THREAD

**Issue by filipkujundzic** [education/GitHubGraduation-2022#7834]
**Hi filipkujundzic,**
**Welcome to graduation!**

### I have a few items I need you to take care of before I can merge this PR:

* *Uh Oh! I've found some issues with where you have created your files!* 
	*Please ensure all changes are contained within the `_data/filipkujundzic/` directory. Invalid file paths:* 

	* `_data/_data/filipkujundzic/filipkujundzic.md`

Feel free to re-request a review from me and I'll come back and take a look!

_Originally posted by @github-education in https://github.com/education/GitHubGraduation-2022/pull/7831#pullrequestreview-985434755_

**Comment by juanpflores** [comment]
I see you got the [✅ Ready for merge](https://github.com/education/GitHubGraduation-2022/labels/%E2%9C%85%20%20Ready%20for%20merge) label on your pull request
