### ISSUE TITLE
Can't fill the shipping form

### ISSUE THREAD

**Issue by synalice** [education/GitHubGraduation-2022#793]
There isn't an option to choose Russia (or Ukraine for that matter) when filling out a shipping form. Does that mean I don't get the candy? 🥺

**Comment by OmarDev100** [comment]
Me too, can't find United Arab Emirates

**Comment by PDPENG** [comment]
Hopefully, more regions can be added

**Comment by harshit2000** [comment]
The maintainers might soon add more regions. Just check if you can temporary fill the form with any other region

**Comment by elisemoe** [comment]
Hello 👋  thank you all for letting us know about the mistake! All three have been added to the form.

Let us know if you notice anymore missing ❤️

**Comment by atik1n** [comment]
> Hello 👋 thank you all for letting us know about the mistake! All three have been added to the form.
> Let us know if you notice anymore missing ❤️

If I already filled form with "Belarus" as country, but in address implicitly written Russia, is it okay?

**Comment by elisemoe** [comment]
> 

I've updated your shipping information. Thanks for letting us know @atik1n!
