### ISSUE TITLE
Already approved for student pack, check fails

### ISSUE THREAD

**Issue by dev-rb** [education/GitHubGraduation-2022#7948]
**Hi dev-rb,**
**Welcome to graduation!**

### I have a few items I need you to take care of before I can merge this PR:

* *I'm not seeing a valid student developer pack approval, please submit an [application](https://education.github.com/discount_requests/student_application?utm_source=2021-06-05-GitHubGraduation) to get started*

Feel free to re-request a review from me and I'll come back and take a look!

_Originally posted by @github-education in https://github.com/education/GitHubGraduation-2022/pull/7857#pullrequestreview-985662613_

I have already been previously approved when I started school. 

![image](https://user-images.githubusercontent.com/43100342/170404494-b3a9bd45-06e2-4292-bf66-212898923088.png)

**Comment by MuhammadSaadSiddique** [comment]
yes same issue with me.

**Comment by juanpflores** [comment]
All issues were reviewed and are in queue to be merged
