### ISSUE TITLE
I think my entry is just skipped

### ISSUE THREAD

**Issue by might4** [education/GitHubGraduation-2022#7971]
Deadline is coming and my pr(#7414) has not yet been merged or even reviewed by a non-bot person. So I'm hoping that somehow my pr will be merged before the deadline comes.

**Comment by hariscs** [comment]
they merged pull #7960 and skipped mine #7492 too

**Comment by HritikR** [comment]
PR is merged https://github.com/education/GitHubGraduation-2022/pull/7414#issuecomment-1139147667

**Comment by ReadChart** [comment]
Mine too, can somebody please help, I have checked the education pack and filled the form, I don't think I'm missing something.

**Comment by juanpflores** [comment]
✅ We've merged all pull request
