### ISSUE TITLE
My PR was skipped, please check my PR: add: Tiger-0512 #7279 

### ISSUE THREAD

**Issue by Tiger-0512** [education/GitHubGraduation-2022#8021]
My graduation month is March in 2022 so my SDP license has expired.
Because of that reason, my PR status is not ready for merge and my PR was skipped.
Please check and merge [my PR](https://github.com/education/GitHubGraduation-2022/pull/7279).

I attach the certificate of my master's degree.
[Certificate.pdf](https://github.com/education/GitHubGraduation-2022/files/8784873/Certificate.pdf)

@elisemoe  & @juanpflores  can you kindly look into this issue?

**Comment by juanpflores** [comment]
✅ the PR was merged
