### ISSUE TITLE
Is the merging PRs procedure completed?

### ISSUE THREAD

**Issue by alperkagankayali** [education/GitHubGraduation-2022#8031]
I checked the description again, which states that the PRs that are merged by 27th of May are eligible to get a custom trading card, stickers and a letter. Since all the timezones are already in the day of 27th, does this mean that the PRs that are not merged yet will not be merged anymore?

**Comment by elisemoe** [comment]
We've extended the deadline until Monday. If you PR has the "Ready to Merge" label, it will be merged then!

**Comment by alperkagankayali** [comment]
Thanks for the info!
