### ISSUE TITLE
Translation improvements

### ISSUE THREAD

**Issue by elB4RTO** [education/GitHubGraduation-2022#8167]
Hello,
I've made a PR to add the italian translation
- [italian](https://github.com/education/GitHubGraduation-2022/pull/8072)

and I've found some unmerged PR for other languages as well
- [french](https://github.com/education/GitHubGraduation-2022/pull/6067)
- [portuguese](https://github.com/education/GitHubGraduation-2022/pull/8101)
- [portuguese](https://github.com/education/GitHubGraduation-2022/pull/6325)
- [marathi](https://github.com/education/GitHubGraduation-2022/pull/7465)

cheers

**Comment by juanpflores** [comment]
Added a few improvements! Waiting for folks to update the issues before moving forward
