### ISSUE TITLE
GitHub Profile Information Deadline

### ISSUE THREAD

**Issue by AlexDev404** [education/GitHubGraduation-2022#8203]
@elisemoe @juanpflores 

Hi,
Just wanted to know when is the deadline for our GitHub profile info that is to be put on the trading card.

That's about it.
Thanks!

**Comment by juanpflores** [comment]
We'll be collecting all data today so it's now or never!

**Comment by AlexDev404** [comment]
@juanpflores Wait wait plss lemme just update my profile photo to something better real quick!

**Comment by AlexDev404** [comment]
@juanpflores Can you use this one that I have currently instead? It would be greatly appreciated if you could...

Thanks in advance for all your patience

**Comment by juanpflores** [comment]
> @juanpflores Can you use this one that I have currently instead? It would be greatly appreciated if you could...
> 
> Thanks in advance for all your patience

I'll try my best to update the image ⭐
