### ISSUE TITLE
Not able to access the Shipping form link

### ISSUE THREAD

**Issue by Maaz10** [education/GitHubGraduation-2022#8209]
Hi all, 

Not able to access the shipping form, but able to access in mobile phone.
Even if registered through mobile device checks fail, (need to submit form)

**Comment by AlexDev404** [comment]
@Maaz10 I think that's because entries have closed already...not too sure though.

**Comment by juanpflores** [comment]
Hi @Maaz10 👋🏼  
Thanks for letting us know about this. I have checked the record on our side and I can see you have submitted a form already. Let us know if you want to change your address to provide an additional form
