### ISSUE TITLE
can't find my profile in _data

### ISSUE THREAD

**Issue by farzanfa** [education/GitHubGraduation-2022#8239]
My pull request was merged  but can't find it on _data. https://github.com/education/GitHubGraduation-2022/pull/644

**Comment by Mohnish226** [comment]
Github limits the number of files that can be viewed in the browser.

> This is an artificial limitation of Github and only impacts viewing via the browser. If you want to see all the files, you need to clone the repository locally.

[Source](https://github.community/t/sorry-we-had-to-truncate-this-directory-to-1000-files-289-entrie-were-omitted-from-the-list/128812/2)

**Comment by lasr21** [comment]
> My pull request was merged but can't find it on _data. #644

https://github.com/education/GitHubGraduation-2022/tree/main/_data/farzanfa :)
