### ISSUE TITLE
When will the Card be provided?

### ISSUE THREAD

**Issue by abhay-ag** [education/GitHubGraduation-2022#8241]
My pull request #7769 was merged a few days ago but I didn't recieve any card in the mail. Please tell when will the card be mailed. 

**Regards**
Abhay Aggarwal

**Comment by abhay-ag** [comment]
> @abhay-ag Cards will be physical. They will be shipped by your mail to your final destination.

Thank you confirming this 😃 !!

**Comment by DHANESHJOSHI** [comment]
I haven't receive my Card in the mail my pull request is #4687 #4677

**Comment by Zesterdock** [comment]
They will be delivered soon as Github graduation event is completed yesterday

**Comment by DHANESHJOSHI** [comment]
And what about the swag ? I haven't got any mail regard swag and card

**Comment by lasr21** [comment]
Hi there, we are still sending the cards for this year's graduation. Please bear with us
