### ISSUE TITLE
Got another person's trading card

### ISSUE THREAD

**Issue by vccheng2001** [education/GitHubGraduation-2022#8284]
Hi, 
I received someone else's (@vishal-patel1) trading card. My username is @vccheng2001 .

![16549906933495008016005812968116](https://user-images.githubusercontent.com/60167936/173208304-0bc50872-a3ca-4fb4-b563-d0cd16c41169.jpg)

**Comment by elisemoe** [comment]
Thanks for letting us know! I've [added an update here](https://github.com/education/GitHubGraduation-2022/issues/8312).
