### ISSUE TITLE
Received wrong trading card

### ISSUE THREAD

**Issue by ZachElkins** [education/GitHubGraduation-2022#8293]
I received @Taowyoo's trading card and letter instead of my own.

![Proof](https://i.imgur.com/GnHhQwF.png)

**Comment by Taowyoo** [comment]
Hi, it seems a common problem. I also received another one's card: @IsaacJade . Create a issue too: #8294

**Comment by elisemoe** [comment]
Thanks for letting us know! I've [added an update here](https://github.com/education/GitHubGraduation-2022/issues/8312).
