### ISSUE TITLE
Received wrong trading card too

### ISSUE THREAD

**Issue by Taowyoo** [education/GitHubGraduation-2022#8294]
I received @IsaacJade 's trading card and letter instead of my own.
![PXL_20220612_174147842](https://user-images.githubusercontent.com/20309719/173246238-ad064ae2-ced1-4820-8d81-3b7958eabf0b.jpg)

**Comment by elisemoe** [comment]
Thanks for letting us know! I've [added an update here](https://github.com/education/GitHubGraduation-2022/issues/8312).
