### ISSUE TITLE
I haven't received my card pls let me know how and when will it be shipped

### ISSUE THREAD

**Issue by hiremathak** [education/GitHubGraduation-2022#8297]

**Comment by mrepol742** [comment]
Same here bro.

**Comment by lasr21** [comment]
Hi there @hiremathak , we are still sending the cards for this year's graduation. Please bear with us

**Comment by icorbrey** [comment]
@lasr21 is there somewhere we can find timelines for when each regions' stuff will be sent out? I'm in Midwest US and have not received anything yet

**Comment by lasr21** [comment]
@icorbrey we are sending them on batches. Sending 7500 customs trading cards takes time 😅

**Comment by icorbrey** [comment]
> @icorbrey we are sending them on batches. Sending 7500 customs trading cards takes time 😅

Totally understandable, thanks for the update! Good luck with all that, it sounds like a logistical nightmare 😂
