### ISSUE TITLE
Incorrect Trading Card Received

### ISSUE THREAD

**Issue by MinicomSoftware** [education/GitHubGraduation-2022#8301]
I got the wrong trading card. I got @stevenrick

**Comment by stevenrick** [comment]
> I got the wrong trading card. I got @stevenrick

And I have not yet received any trading card. Thanks for reporting this @MinicomSoftware

**Comment by elisemoe** [comment]
Thanks for letting us know! I've [added an update here](https://github.com/education/GitHubGraduation-2022/issues/8312).
