### ISSUE TITLE
Received wrong announcement and trading card.

### ISSUE THREAD

**Issue by fbscott** [education/GitHubGraduation-2022#8304]
I received the wrong announcement and trading card.

Fire the intern!

![IMG_20220613_173641](https://user-images.githubusercontent.com/4388162/173464737-11858fd6-0050-4018-9757-a5f50a05371f.jpg)

**Comment by fbscott** [comment]
@github-education Plans to resend?

**Comment by elisemoe** [comment]
Thanks for letting us know! I've [added an update here](https://github.com/education/GitHubGraduation-2022/issues/8312).
