### ISSUE TITLE
Wrong trading card recieved

### ISSUE THREAD

**Issue by IsaacJade** [education/GitHubGraduation-2022#8307]
I received the card meant for @Youssef-Beltagy

**Comment by Youssef-Beltagy** [comment]
And I was wondering when I would get it. Thank you for opening an issue. I wonder if/when they will see this issue.

**Comment by Youssef-Beltagy** [comment]
Can you please assign someone to this issue?

**Comment by IsaacJade** [comment]
I can't add assignees. But you can @ people here

**Comment by elisemoe** [comment]
Thanks for letting us know! I've [added an update here](https://github.com/education/GitHubGraduation-2022/issues/8312).
