### ISSUE TITLE
Wrong trading card and letter

### ISSUE THREAD

**Issue by savannanoh** [education/GitHubGraduation-2022#8308]
Same issue as others. I received the trading card and letter meant for @sauravkumr

**Comment by fbscott** [comment]
I got yours! https://github.com/education/GitHubGraduation-2022/issues/8304#issue-1270075827

**Comment by AlexDev404** [comment]
> @savannanoh, I got yours! [#8304 (comment)](https://github.com/education/GitHubGraduation-2022/issues/8304#issue-1270075827)

This has just got to be GitHub's worst messup in the history of mankind 😭

**Comment by AlexDev404** [comment]
@juanpflores !!! 

Fire the intern!! 🤣

**Comment by Zesterdock** [comment]
> > Is there anything else other then the card
> 
> a announcement letter of sorts, you can check out other issues to see how they look like.

Have you got it

**Comment by elisemoe** [comment]
Thanks for letting us know! I've [added an update here](https://github.com/education/GitHubGraduation-2022/issues/8312).
