### ISSUE TITLE
I cannot find my name in the yearbook of GitHub Graduation 2022

### ISSUE THREAD

**Issue by Abhishek786-Kolvekar** [education/GitHubGraduation-2022#8309]
Hello,
I had submitted my pull request and it was even merged the next day. Also I was one among 7500 participants to get the PR merged.
But I am unable to find my name in the yearbook.
Please address this issue.
Regards

**Comment by Abhishek786-Kolvekar** [comment]
@elisemoe @fbscott

**Comment by Abhishek786-Kolvekar** [comment]
https://github.com/education/GitHubGraduation-2022/pull/5274

**Comment by Mohnish226** [comment]
@Abhishek786-Kolvekar Here's a [link](https://education.github.com/graduation/yearbook?sort=az&page=2&search=Abhishek786-Kolvekar#Abhishek786-Kolvekar) to your yearbook profile:
https://education.github.com/graduation/yearbook?sort=az&page=2&search=Abhishek786-Kolvekar#Abhishek786-Kolvekar

**Comment by diwasatreya** [comment]
> Hello, I had submitted my pull request and it was even merged the next day. Also I was one among 7500 participants to get the PR merged. But I am unable to find my name in the yearbook. Please address this issue. Regards

You have to search your full GitHub username `Abhishek786-Kolvekar` then it will redirect to your section. Searching `Abhishek786` or `Kolvekar` will not give the result.

**Comment by Abhishek786-Kolvekar** [comment]
Thanks for addressing my queries.
@diwasatreya @Mohnish226

**Comment by ZCyueternal** [comment]
#4746 My pull request has been merged .
unable to find my name in the yearbook, too
Does anyone can help me?
Thanks!!!

**Comment by ZCyueternal** [comment]
> > Hello, I had submitted my pull request and it was even merged the next day. Also, I was one among 7500 participants to get the PR merged. But I am unable to find my name in the yearbook. Please address this issue. Regards
> 
> You have to search your full GitHub username `Abhishek786-Kolvekar` then it will redirect to your profile yearbook. Searching `Abhishek786` or `Kolvekar` will not give the result.

Thanks bro.
I should type FULL name of my account name.

**Comment by ZCyueternal** [comment]
https://education.github.com/graduation/yearbook?sort=az&page=22&search=ZCyueternal#ZCyueternal
This is mine.

**Comment by diwasatreya** [comment]
> > > Hello, I had submitted my pull request and it was even merged the next day. Also, I was one among 7500 participants to get the PR merged. But I am unable to find my name in the yearbook. Please address this issue. Regards
> > 
> > 
> > You have to search your full GitHub username `Abhishek786-Kolvekar` then it will redirect to your profile yearbook. Searching `Abhishek786` or `Kolvekar` will not give the result.
> 
> Thanks bro. I should type FULL name of my account name.

Yeah, welcome bro
