### ISSUE TITLE
no card received 

### ISSUE THREAD

**Issue by ishikabansal04** [education/GitHubGraduation-2022#8310]
I would like to ask when the gift will be delivered, and I did not receive the card in the mailbox. My PR #1997 merged on 5th May 2022

**Comment by diwasatreya** [comment]
They have started delivering and it depends according to your country. It may take a week I guess

**Comment by ZCyueternal** [comment]
Will the card be sent to China? I'm a developer from China. Thanks

**Comment by prabincankod** [comment]
@diwasatreya did you get yours?

**Comment by diwasatreya** [comment]
> @diwasatreya did you get yours?

@prabincankod  pa xhaina yaar bro Nepal ma kaile aauni kaile :laughing:

**Comment by prabincankod** [comment]
> Hi there @ishikabansal04 , we are still sending the cards for this year's graduation. Bear with us

what about the shipping in nepal??
