### ISSUE TITLE
Wrong card sent

### ISSUE THREAD

**Issue by AmACircle** [education/GitHubGraduation-2022#8311]
I received @blackbird71SR's card instead of my own
![blsck](https://user-images.githubusercontent.com/66957644/173665056-5d0b87df-65c2-459d-aabc-1e1a6371003d.jpg)
.

**Comment by elisemoe** [comment]
Thanks for letting us know! I've [added an update here](https://github.com/education/GitHubGraduation-2022/issues/8312).
