### ISSUE TITLE
Wrong Trading Card Thread 🧵😱

### ISSUE THREAD

**Issue by elisemoe** [education/GitHubGraduation-2022#8312]
Hi everyone -- there's been a mistake with trading cards shipped within the United States. If you are in the US, you likely received the wrong card.

Our team is reprinting cards and getting them in the mail as soon as possible. You do not need to send the card you received anywhere. 

Thanks for your patience and understanding 💖

**Comment by DHANESHJOSHI** [comment]
Hello, when we will get i'm form india

**Comment by fbscott** [comment]
@DHANESHJOSHI, This only affects U.S. recipients.

**Comment by DHANESHJOSHI** [comment]
But what about the mail still I haven't received any mail

**Comment by DHANESHJOSHI** [comment]
@fbscott I don't think so because other Indians are getting their card.

**Comment by ZCyueternal** [comment]
https://github.com/education/GitHubGraduation-2022/pull/4746
Will the card be sent to China?

**Comment by ullaskunder3** [comment]
> #4746 Will the card be sent to China?

@ZCyueternal don't worry... @github-education working really hard. let's wait :)

**Comment by ritesh-kanchi** [comment]
Hi, I was told to add my PR number to this issue: #2502

**Comment by Max094Reikeb** [comment]
I still haven't received my card... I'm from France!

**Comment by xMdb** [comment]
Still haven't got mine in Australia?

**Comment by DHANESHJOSHI** [comment]
Still haven't got mine in India ?

**Comment by MishaAkram** [comment]
Still haven't got mine in Pakistan?

**Comment by DHANESHJOSHI** [comment]
Didn't got my geeks ? I'm from India

**Comment by itxshakil** [comment]
I am from India, I also didn't get any mail, and also no tracking number or anything has been provided since.

**Comment by lasr21** [comment]
We're seeing up to 5 month delivery times for international shipments with the delays from covid. If you have not seen anything by then, you're welcome to get back in touch with us.

Unfortunately, we don't have tracking on the shipments.

**Comment by DHANESHJOSHI** [comment]
Thank you GitHub i received my card but didn't got any swags yet my pr is #4677

**Comment by lasr21** [comment]
> Thank you GitHub i received my card but didn't got any swags yet my pr is #4677

@DHANESHJOSHI we only send the card :)

**Comment by SupaliOjha** [comment]
I am from India and I didn't get any swags or mail yet. My PR is #4947

**Comment by lasr21** [comment]
> I am from India and I didn't get any swags or mail yet. My PR is #4947

Hello, On the first week of September, we will send a form to resend the missing cards. Stay tuned. Thanks for your patience
