### ISSUE TITLE
Received Wrong Trading Card

### ISSUE THREAD

**Issue by TaylorH00** [education/GitHubGraduation-2022#8324]
Hello, 

My pull request was #4529  and I happened to receive the user's, "DumbassNamedTuna", trading card. Anyways, any help would be appreciated! 

Thank you,
Taylor H

**Comment by rubencosta13** [comment]
@TaylorH00 Kindly take a look at this issue please 
https://github.com/education/GitHubGraduation-2022/issues/8312
