### ISSUE TITLE
Card not Received 

### ISSUE THREAD

**Issue by HaidarAli16** [education/GitHubGraduation-2022#8330]
When will be the cards dispatched for Pakistan

**Comment by rubencosta13** [comment]
kindly wait, you will eventually get your trading card, github is working hardly to deliver them

**Comment by AlexDev404** [comment]
> kindly wait, you will eventually get your trading card, github is working hardly to deliver them

Love how you said "hardly" there lol

**Comment by rubencosta13** [comment]
> > kindly wait, you will eventually get your trading card, github is working hard to deliver them
> 
> Love how you said "hardly" there lol

Not sure what you are talking about 😂

**Comment by lasr21** [comment]
we are still sending the cards for this year's graduation. Bear with us
