### ISSUE TITLE
Custom Card Shipment

### ISSUE THREAD

**Issue by jackgraddon** [education/GitHubGraduation-2022#8334]
Hello, I have not yet received the custom trading card in the mail yet. I was wondering if they have been shipped or if there was an issue with mine?

My PR is here:
https://github.com/education/GitHubGraduation-2022/issues/6305#issuecomment-1166392261

**Comment by rubencosta13** [comment]
Kindly await, you will get your trading card, github education is working hard to deliver them all

**Comment by DHANESHJOSHI** [comment]
i don't think so the card will come even I haven't got any mail or card yeat 

MY PR IS = #4677 (DHANESHJOSHI)

**Comment by lasr21** [comment]
we are still sending the cards for this year's graduation. Bear with us

**Comment by jackgraddon** [comment]
> we are still sending the cards for this year's graduation. Bear with us

Awesome, thank you! Excited to receive it.
