### ISSUE TITLE
Going on vacation

### ISSUE THREAD

**Issue by Omar8345** [education/GitHubGraduation-2022#8347]
Hello @education team!

**I'll be travelling next month and I am not sure if I will receive my swag this month or not, I prefer to delay it to be delivered on September**.

@elisemoe

**Comment by lasr21** [comment]
Hi there, we have already sent all the cards. Postal service in each region it's different. Some arrive in weeks. Other takes months. It's out of our control.

**Comment by Omar8345** [comment]
That's okay, may I have the tracking code and the carrier to report to the postal company in my country?

**Comment by hashfx** [comment]
> That's okay, may I have the tracking code and the carrier to report to the postal company in my country?

I doubt if they receive or provide any tracking code. They have addressed the same in other issues too

**Comment by lasr21** [comment]
> That's okay, may I have the tracking code and the carrier to report to the postal company in my country?

Unfortunately, we don't have tracking on the shipments

**Comment by Omar8345** [comment]
At least like package code, etc. to identify it, so I can report to my postal in the country
