### ISSUE TITLE
Did not recieve the Card!!

### ISSUE THREAD

**Issue by abhay-ag** [education/GitHubGraduation-2022#8348]
Hii GitHub,
My pull request #7769 was merged on 27th May, but I haven't got the cards till now. I am from India. Please Help !!!!!

**Comment by ullaskunder3** [comment]
80% of us didn't received their card they doing their best, I think this time something went wrong, lets wait and hope

**Comment by abhay-ag** [comment]
> 80% of us didn't received their card they doing their best, I think this time something went wrong, lets wait and hope

Waiting 😀. Hope they arrive soon!!

**Comment by lasr21** [comment]
We're seeing up to 5 month delivery times for international shipments with the delays from covid. If you have not seen anything by then, you're welcome to get back in touch with us.

Unfortunately, we don't have tracking on the tier one shipments.
