### ISSUE TITLE
Swag Shipment

### ISSUE THREAD

**Issue by Ajithkumar7925** [education/GitHubGraduation-2022#8351]
**When the swags will get shipped to India?**

**Comment by hashfx** [comment]
> **When the swags will get shipped to India?**

**+1**

**Comment by C19H3R** [comment]
+1

**Comment by Abhishek786-Kolvekar** [comment]
+1

**Comment by rubencosta13** [comment]
I've read on an issue that overseas (out of the US) shipments can take up to 5 months to arrive at the final destination.

Github isn't like amazon.... We gotta wait, you're in the same boat as me

_Originally posted by @rubencosta13 in https://github.com/education/GitHubGraduation-2022/issues/8353#issuecomment-1192689370_

**Comment by silicon-ninja** [comment]
Dope I will get very old by the time it reaches india thank you microsoft
