### ISSUE TITLE
I haven't received graduation card yet

### ISSUE THREAD

**Issue by imranbarbhuiya** [education/GitHubGraduation-2022#8352]
my pr https://github.com/education/GitHubGraduation-2022/pull/4291

**Comment by rubencosta13** [comment]
I've read on an issue that overseas (out of the US) shipments can take up to 5 months to arrive at the final destination.

Github isn't like amazon.... We gotta wait, you're in the same boat as me

_Originally posted by @rubencosta13 in https://github.com/education/GitHubGraduation-2022/issues/8353#issuecomment-1192689370_

**Comment by imranbarbhuiya** [comment]
@lasr21 I didn't receive my card yet. Is it normal?

**Comment by rubencosta13** [comment]
Take a look at #8395

**Comment by imranbarbhuiya** [comment]
Ty
