### ISSUE TITLE
I have not received graduation card and swags yet.

### ISSUE THREAD

**Issue by Lucifer1130** [education/GitHubGraduation-2022#8353]
Please look into the matter.

**Comment by rubencosta13** [comment]
I've read on an issue that overseas (out of the US) shipments can take up to 5 months to arrive at the final destination.

Github isn't like amazon.... We gotta wait, you're in the same boat as me

**Comment by Lucifer1130** [comment]
> I've read on an issue that overseas (out of the US) shipments can take up to 5 months to arrive at the final destination.
> 
> Github isn't like amazon.... We gotta wait, you're in the same boat as me

Waiting is a tiring process , nevertheless if it's for good then let us.
