### ISSUE TITLE
Didn't Got my trading card And Swag #386

### ISSUE THREAD

**Issue by HarishGuragol** [education/GitHubGraduation-2022#8359]
Hello sir

I have not received the shipment of my graduation swags 2022. I have filled out both the forms, can you please update on it @lasr21
Username: HarishGuragol
PR https://github.com/education/GitHubGraduation-2022/pull/386

**Comment by lasr21** [comment]
> Hello sir
> 
> I have not received the shipment of my graduation swags 2022. I have filled out both the forms, can you please update on it @lasr21 Username: HarishGuragol PR #386

Congrats on your graduation! ✨ We're seeing up to 5 month delivery times for international shipments with the delays from covid. If you have not seen anything by then, you're welcome to get back in touch with us.

Unfortunately, we don't have tracking on the shipments.
