### ISSUE TITLE
Can I get update on my Trading card and swag ?

### ISSUE THREAD

**Issue by suyashvash** [education/GitHubGraduation-2022#8361]
I want to get some updates on my swag as I Updated my bio for it. If it is not delivered or made yet, It would be great.
username - @suyashvash

**Comment by lasr21** [comment]
> I want to get some updates on my swag as I Updated my bio for it. If it is not delivered or made yet, It would be great. username - @suyashvash

Congrats on your graduation! ✨ We're seeing up to 5 month delivery times for international shipments with the delays from covid. If you have not seen anything by then, you're welcome to get back in touch with us.

Unfortunately, we don't have tracking on the shipments.

**Comment by C19H3R** [comment]
also is there a way with which i can check what address i gave i have a doubt that autofill  filled the wrong address

**Comment by suyashvash** [comment]
Well update from my side, just received the package today.. Lol
