### ISSUE TITLE
Haven't received the mail with the verification code to the package.

### ISSUE THREAD

**Issue by Hetarth02** [education/GitHubGraduation-2022#8369]
Hello, I haven't recieved the verification code in mail or text message. Is there something wrong, can you regenerate or resend me the code?

I contacted the courier services(DTDC) but they said that the tracking number is necessary otherwise they won't be able to help.

Can anyone help me regarding this matter?

**Comment by suyashvash** [comment]
Guess who won’t be graduating this year LOL.

**Comment by lasr21** [comment]
Congrats on your graduation! @Hetarth02  ✨ We're seeing up to 5 month delivery times for international shipments with the delays from covid. If you have not seen anything by then, you're welcome to get back in touch with us.

Unfortunately, we don't have tracking on the shipments.

**Comment by Hetarth02** [comment]
@lasr21  Actually, the package was sent to my address but due to some confusion it was again deported back to the head branch. Now, I am struggling to get it back as they are asking for the tracking/shipment number. Can you help me with this please?
Thanks!

**Comment by lasr21** [comment]
@arkodyuti can you help us with this issue? 👀

**Comment by arkodyuti** [comment]
Hi @Hetarth02 👋🏻 we will work with our shipping partner to resend this to your address. Thanks ✨
