### ISSUE TITLE
No Trading Card Received Yet [INDIA]

### ISSUE THREAD

**Issue by itxshakil** [education/GitHubGraduation-2022#8370]
Neither I got any mail of the trading nor any tracking number or so since.

Does anyone have an idea when we will get it in India?

**Comment by itxshakil** [comment]
#7919 My pull request

**Comment by lasr21** [comment]
Congrats on your graduation! @itxshakil  ✨ We're seeing up to 5 month delivery times for international shipments with the delays from covid. If you have not seen anything by then, you're welcome to get back in touch with us.

Unfortunately, we don't have tracking on the shipments.
