### ISSUE TITLE
Re-Print GitHub Graduation Swag 2022

### ISSUE THREAD

**Issue by lasr21** [education/GitHubGraduation-2022#8395]
Re-Print GitHub Graduation card. We are aware that some of you have not received the card yet. We are opening a form for a reprint. We will keep it open until Oct 07. 

Please only fill out the form if you have not received your card. [Form](https://airtable.com/shrq4pObYbyaxwlpD)

**Comment by EyeRunnMan** [comment]
Also what happens in this case since that time https://github.com/education/GitHubGraduation-2022/pull/404 my user Name was C19H3R and now I have got my username changed to EyeRunnMan 

P.S. I haven't received any swags or updates regarding it.

**Comment by rubencosta13** [comment]
Submitted

**Comment by Peiprjs** [comment]
Will we get email updates?

**Comment by lasr21** [comment]
> EyeRunnMan

we will print it with the new usrname

**Comment by lasr21** [comment]
> Will we get email updates?

We will close the form this week and start the process of reprint.

**Comment by OmarDev100** [comment]
Oof I just saw this now 😭😭😭

**Comment by MusfiqDehan** [comment]
Hi @lasr21 ,

I noticed this issue today.  I thought I would receive email updates for the "Re-Print of GitHub Graduation Swag 2022"; that's why I didn't follow this repo properly. I know it's my mistake. But if possible, can you kindly **reopen** the re-print form for at least one week, please? Sorry for bothering you again.

Regards,
Md. Musfiqur Rahaman
PR #1282

**Comment by lasr21** [comment]
> Hi @lasr21 ,
> 
> I noticed this issue today. I thought I would receive email updates for the "Re-Print of GitHub Graduation Swag 2022"; that's why I didn't follow this repo properly. I know it's my mistake. But if possible, can you kindly **reopen** the re-print form for at least one week, please? Sorry for bothering you again.
> 
> Regards, Md. Musfiqur Rahaman PR #1282


We are so sorry :S we closed the form past Friday.

**Comment by lasr21** [comment]
Thank you to everyone who fills the form. We are processing the responses and starting the process. 

Remember that shipping takes time and depends on every country.

**Comment by Hetarth02** [comment]
> Thank you to everyone who fills the form. We are processing the responses and starting the process. 
> 
> Remember that shipping takes time and depends on every country. 

Hey @lasr21 , any updates regarding this?

**Comment by itxshakil** [comment]
> Thank you to everyone who fills the form. We are processing the responses and starting the process.
> 
> Remember that shipping takes time and depends on every country.

Hey @lasr21 , any updates regarding this?

**Comment by itxshakil** [comment]
> Thank you to everyone who fills the form. We are processing the responses and starting the process.
> 
> Remember that shipping takes time and depends on every country.

Hey @lasr21 , any updates regarding the shipment?

Did anyone received the reprinted shipment yet?

**Comment by lasr21** [comment]
@Hetarth02 @itxshakil we just sent all the cards it will take a while, if you fill the form we sent again your card to the postal office :)

**Comment by Hetarth02** [comment]
> @Hetarth02 @itxshakil we just sent all the cards it will take a while, if you fill the form we sent again your card to the postal office :)

Thanks for replying back, but I just received my package. Thank you for all the help!

**Comment by Hetarth02** [comment]
> > Thank you to everyone who fills the form. We are processing the responses and starting the process.
> > 
> > Remember that shipping takes time and depends on every country.
> 
> Hey @lasr21 , any updates regarding the shipment?
> 
> Did anyone received the reprinted shipment yet?

Yeah, I received it!

**Comment by itxshakil** [comment]
Congrats, you got yours.  I hope I get mine soon too. Although I have lose the hope. Lets see.

**Comment by Peiprjs** [comment]
> Congrats, you got yours. I hope I get mine soon too. Although I have lose the hope. Lets see.

Unfortunately, I have lost hope too. What company have you used for shipping? It should not be taking this long...

**Comment by sky-ezequielsantos** [comment]
@lasr21 I just saw this thread today. Any chance to fill the form again? I did not receive (Portugal) the card or the email advising about the thread.

**Comment by kartikeya999** [comment]
@lasr21 I filled out this form in the month of September but I haven't received the card till now.
Can you please check on this?

**Comment by Peiprjs** [comment]
It **IS** getting pretty annoying.

**Comment by lasr21** [comment]
Howdie, we sent the cards via the postal service; if you filled out the form, we sent your card again.  It depends on each country's postal service for the delivery :S

**Comment by kartikeya999** [comment]
@lasr21 Still no update regarding delivery status.

**Comment by kartikeya999** [comment]
@lasr21 Still no update regarding delivery status.

**Comment by frxdude** [comment]
Didn't recieve Re-Print email. What should i do now. thank you @lasr21

**Comment by Peiprjs** [comment]
Yeah not even an email. That would have been nice at least.

> @lasr21 Still no update regarding delivery status.
