### ISSUE TITLE
No updates on the swag!!

### ISSUE THREAD

**Issue by appledora** [education/GitHubGraduation-2022#8409]
Hi, my PR got accepted and merged on the first try and everything. I had also filled up the swag form on time. But haven't heard back since :| My friend and I had consecutive PRs (and from the same country) and he just received his swags today, while I haven't had any updates at all :| Could you kindly tell me what's going on? :( 

This is the link to [my PR](https://github.com/education/GitHubGraduation-2022/pull/7811)

**Comment by appledora** [comment]
@github-education

**Comment by lasr21** [comment]
please check https://github.com/education/GitHubGraduation-2022/issues/8395

**Comment by appledora** [comment]
THANKS @lasr21 !! I had totally missed it :|
