### ISSUE TITLE
Swags not delivered and no updates by mail

### ISSUE THREAD

**Issue by 0xN0x** [education/GitHubGraduation-2022#8419]
Hello, 

My PR : #4147 
The shipment was to France so maybe it will take a few month and is normal ?
I had no update by email or anything so far so i don't know if it's normal or not and who i need to contact for this if it isn't.

Thanks you in advance

**Comment by bymicah** [comment]
Same to me as well. I still do not receive my swags. I'm from PH.

**Comment by ZekeriyaAY** [comment]
Me too, from Turkey.

**Comment by rootwhois** [comment]
Me too, from China.

**Comment by soxft** [comment]
Me too, from China.

**Comment by lasr21** [comment]
We're sorry to hear that you hadn't received the GitHub Graduation swag from May. The Education team were aware that some graduates did not receive their trading card. To accommodate this we requested any graduates to https://github.com/education/GitHubGraduation-2022/issues/8395 before October 7th 2022 to receive a re-printing of swag. Unfortunately this form is now closed. This may not be the response you had hoped for but we appreciate you taking part in the GitHub Graduation 2022!

**Comment by bymicah** [comment]
@lasr21 Hello. I was able to answer the form, before September 30, for re-printing but did not received anything.

**Comment by rootwhois** [comment]
@lasr21 Hi, could you please help us to provide the tracking number, we can try to track the current delivery status by ourselves.

**Comment by lasr21** [comment]
> @lasr21 Hello. I was able to answer the form, before September 30, for re-printing but did not received anything.

We are sending the cards; it takes time. We send it via postal service and depending on each country.

**Comment by lasr21** [comment]
> @lasr21 Hi, could you please help us to provide the tracking number, we can try to track the current delivery status by ourselves.

@rootwhois unfortunately we don't have tracking numbers.
