### ISSUE TITLE
Swags not delivered and no information yet

### ISSUE THREAD

**Issue by deltapsifi** [education/GitHubGraduation-2022#8421]
I live in India and my swags haven't been delivered yet, but my friend, who lives in the same state as me, got his swags delivered.

**Comment by clonalejandro** [comment]
me too Im from Spain

**Comment by lasr21** [comment]
We're sorry to hear that you hadn't received the GitHub Graduation swag from May. The Education team were aware that some graduates did not receive their trading card. To accommodate this we requested any graduates to https://github.com/education/GitHubGraduation-2022/issues/8395 before October 7th 2022 to receive a re-printing of swag. Unfortunately this form is now closed. This may not be the response you had hoped for but we appreciate you taking part in the GitHub Graduation 2022!

**Comment by dipesh88** [comment]
I also haven't yet, I'm from Chandigarh India
https://www.linkedin.com/in/dipesh-singla/
